version: "3.9"
services:
  app:
    build: .
    ports:
      - 9000:9000
    links:
      - elasticsearch:elasticsearch
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "mkdir -p ./var/log ./var/temp && composer install && php -S 0.0.0.0:9000 -t ./public"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms750m -Xmx750m
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    ports:
      - 9001:5601
